import { ACTIVE_TAB } from "../../utils/consts";
import {
  ADD_TRIP,
  ADD_TRIP_OWN,
  ADD_TRIP_OWN_REQUEST,
  ADD_TRIP_OWN_REQUEST_ERROR,
  ADD_TRIP_OWN_REQUEST_SUCCESS,
  ADD_TRIP_REQUEST,
  ADD_TRIP_REQUEST_ERROR,
  ADD_TRIP_REQUEST_SUCCESS,
  GET_TRIPS_FOR_CALENDAR_REQUEST,
  GET_TRIPS_FOR_CALENDAR_REQUEST_ERROR,
  GET_TRIPS_FOR_CALENDAR_REQUEST_SUCCESS,
  GET_TRIPS_REQUEST,
  GET_TRIPS_REQUEST_ERROR,
  GET_TRIPS_REQUEST_SUCCESS,
  REMOVE_TRIP_REQUEST,
  REMOVE_TRIP_REQUEST_ERROR,
  REMOVE_TRIP_REQUEST_SUCCESS,
  SET_CURRENT_TAB,
  SET_TRIP_FOR_SETTINGS,
} from "../actions/trips";

const initialState = {
  currentTab: ACTIVE_TAB,
  // trips: [
  //   {
  //     id: 10,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-09T10:28:41.173Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "delegated",
  //     status: "confirmed",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-09T10:28:41.173Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 0,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-09T10:28:41.173Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "delegated",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-09T10:28:41.173Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 110,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-09T10:28:41.173Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "delegated",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-09T10:28:41.173Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 10,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-09T10:28:41.173Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "delegated",
  //     status: "confirmed",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-09T10:28:41.173Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 0,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-09T10:28:41.173Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "delegated",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-09T10:28:41.173Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 110,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-09T10:28:41.173Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "delegated",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-09T10:28:41.173Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-09T10:28:41.173Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-09T10:28:41.173Z",
  //       updated_at: "2025-12-09T10:28:41.173Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  // ],
  trips: null,
  getTripsRequest: false,
  getTripsRequestError: false,

  addTripRequest: false,
  addTripRequestError: false,

  tripForSettings: null,

  removeTripRequest: false,
  removeTripRequestError: false,

  // tripsForCalendar: [
  //   {
  //     id: 1,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-06T07:42:03.042Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "own",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2024-12-01T07:42:03.042Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 2,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-06T07:42:03.042Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "own",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2024-12-01T07:42:03.042Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T19:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T19:42:03.042Z",
  //       updated_at: "2025-12-06T19:42:03.042Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 8,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2025-12-07T07:42:03.042Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "own",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2024-12-01T07:42:03.042Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T19:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T19:42:03.042Z",
  //       updated_at: "2025-12-06T19:42:03.042Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 3,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2026-01-01T07:42:03.042Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "own",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-06T07:42:03.042Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 4,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2026-01-01T07:42:03.042Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "own",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-06T07:42:03.042Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 5,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2026-01-01T07:42:03.042Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "own",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-06T07:42:03.042Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  //   {
  //     id: 6,
  //     creator_id: 0,
  //     driver_id: 0,
  //     vehicle_id: 0,
  //     from_address: "string",
  //     to_address: "string",
  //     passenger_phone_number: "string",
  //     departure_datetime: "2026-01-01T07:42:03.042Z",
  //     price: 0,
  //     total_seats: 0,
  //     car_class: "passenger_car",
  //     description: "string",
  //     trip_type: "own",
  //     status: "published",
  //     delegation_commission: 0,
  //     is_delegation_active: true,
  //     created_at: "2025-12-06T07:42:03.042Z",
  //     driver: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     creator: {
  //       username: "string",
  //       first_name: "string",
  //       last_name: "string",
  //       phone_number: "string",
  //       id: 0,
  //       telegram_id: 0,
  //       role: "passenger",
  //       is_active: true,
  //       is_verified: true,
  //       subscription_exp: "2025-12-06T07:42:03.042Z",
  //       sbp_bank: "string",
  //       sbp_phone_number: "string",
  //       rating_avg: 0,
  //       rating_count: 0,
  //       created_at: "2025-12-06T07:42:03.042Z",
  //       updated_at: "2025-12-06T07:42:03.042Z",
  //     },
  //     vehicle: {
  //       brand: "string",
  //       model: "string",
  //       year: 0,
  //       color: "string",
  //       license_plate: "string",
  //       additional_info: "string",
  //       car_class: "passenger_car",
  //       id: 0,
  //       driver_id: 0,
  //       photo_url: "string",
  //       is_active: true,
  //     },
  //   },
  // ],
  tripsForCalendar: null,
  getTripsForCalendarRequest: false,
  getTripsForCalendarRequestError: false,

  addTripOwnRequest: false,
  addTripOwnRequestError: false,
};

export const tripsReducer = (state = initialState, action) => {
  switch (action.type) {
    case ADD_TRIP_OWN_REQUEST:
      return {
        ...state,
        addTripOwnRequest: true,
        addTripOwnRequestError: false,
      };
    case ADD_TRIP_OWN_REQUEST_ERROR:
      return {
        ...state,
        addTripOwnRequest: false,
        addTripOwnRequestError: true,
      };
    case ADD_TRIP_OWN_REQUEST_SUCCESS:
      return {
        ...state,
        addTripOwnRequest: false,
        addTripOwnRequestError: false,
      };
    case ADD_TRIP_OWN:
      return {
        ...state,
        tripsForCalendar: [...state.tripsForCalendar, action.newTrip],
      };

    case GET_TRIPS_FOR_CALENDAR_REQUEST:
      return {
        ...state,
        getTripsForCalendarRequest: true,
        getTripsForCalendarRequestError: false,
      };
    case GET_TRIPS_FOR_CALENDAR_REQUEST_ERROR:
      return {
        ...state,
        getTripsForCalendarRequest: false,
        getTripsForCalendarRequestError: true,
      };
    case GET_TRIPS_FOR_CALENDAR_REQUEST_SUCCESS:
      return {
        ...state,
        tripsForCalendar: action.trips,
        getTripsForCalendarRequest: false,
        getTripsForCalendarRequestError: false,
      };
    case REMOVE_TRIP_REQUEST:
      return {
        ...state,
        removeTripRequest: true,
        removeTripRequestError: false,
      };

    case REMOVE_TRIP_REQUEST_ERROR:
      return {
        ...state,
        removeTripRequest: false,
        removeTripRequestError: true,
      };

    case REMOVE_TRIP_REQUEST_SUCCESS:
      return {
        ...state,
        trips: [
          ...state.trips.filter((trip) => {
            if (trip.id !== action.idTripForRemove) {
              return trip;
            }
          }),
        ],
        removeTripRequest: false,
        removeTripRequestError: false,
      };

    case SET_TRIP_FOR_SETTINGS:
      return {
        ...state,
        tripForSettings: action.tripForSettings,
      };

    case SET_CURRENT_TAB:
      return {
        ...state,
        currentTab: action.currentTab,
      };
    case GET_TRIPS_REQUEST:
      return {
        ...state,
        getTripsRequest: true,
        getTripsRequestError: false,
      };
    case GET_TRIPS_REQUEST_ERROR:
      return {
        ...state,
        getTripsRequest: false,
        getTripsRequestError: true,
      };
    case GET_TRIPS_REQUEST_SUCCESS:
      return {
        ...state,
        trips: action.trips,
        getTripsRequest: false,
        getTripsRequestError: false,
      };

    case ADD_TRIP:
      return {
        ...state,
        trips: [...state.trips, action.newTrip],
      };
    case ADD_TRIP_REQUEST:
      return {
        ...state,
        addTripRequest: true,
        addTripRequestError: false,
      };
    case ADD_TRIP_REQUEST_ERROR:
      return {
        ...state,
        addTripRequest: false,
        addTripRequestError: true,
      };
    case ADD_TRIP_REQUEST_SUCCESS:
      return {
        ...state,
        addTripRequest: false,
        addTripRequestError: false,
      };

    default:
      return state;
  }
};
