name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy via SCP and set permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 1045
          script: |
            # Создаем директорию если не существует
            mkdir -p /home/aleks/VKR/dist

            # Копируем файлы с помощью scp
            scp -r -o StrictHostKeyChecking=no /github/workspace/dist/* /home/aleks/VKR/dist/

            # Устанавливаем права
            echo '${{ secrets.VPS_ALEKS_PASSWORD }}' | sudo -S chown -R www-data:www-data /home/aleks/VKR/dist
            echo '${{ secrets.VPS_ALEKS_PASSWORD }}' | sudo -S chmod -R 755 /home/aleks/VKR/dist
            echo '${{ secrets.VPS_ALEKS_PASSWORD }}' | sudo -S systemctl reload nginx
